// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0aCVGDKegfxQg3c9yXi_BGA4zV7RNJzg',
    appId: '1:698388626414:ios:d8ff5099d1c4cebe536cff',
    messagingSenderId: '698388626414',
    projectId: 'espcontroller-79a40',
    databaseURL: 'https://espcontroller-79a40-default-rtdb.firebaseio.com',
    storageBucket: 'espcontroller-79a40.firebasestorage.app',
    iosBundleId: 'com.example.jpsc.espcontroller',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADbxTSwW0jbroj1AjDFvlfy8xnyPBecCo',
    appId: '1:311977436929:web:0a2e6b75c51b342be85d00',
    messagingSenderId: '311977436929',
    projectId: 'flutterespcontroller',
    authDomain: 'flutterespcontroller.firebaseapp.com',
    databaseURL: 'https://flutterespcontroller-default-rtdb.firebaseio.com',
    storageBucket: 'flutterespcontroller.firebasestorage.app',
    measurementId: 'G-QF94CZQ04E',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9vPwdxPsciwNh4w9uSdVkIYmmu2vHIK4',
    appId: '1:311977436929:ios:2dd507412a233dfce85d00',
    messagingSenderId: '311977436929',
    projectId: 'flutterespcontroller',
    databaseURL: 'https://flutterespcontroller-default-rtdb.firebaseio.com',
    storageBucket: 'flutterespcontroller.firebasestorage.app',
    iosBundleId: 'com.example.jpsc.espcontroller',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt0Lnc-3kqwkLpaOnNSBEGONsZnUyBlUA',
    appId: '1:311977436929:android:3900eaebd693ab79e85d00',
    messagingSenderId: '311977436929',
    projectId: 'flutterespcontroller',
    databaseURL: 'https://flutterespcontroller-default-rtdb.firebaseio.com',
    storageBucket: 'flutterespcontroller.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADbxTSwW0jbroj1AjDFvlfy8xnyPBecCo',
    appId: '1:311977436929:web:c86d093c9b660f1fe85d00',
    messagingSenderId: '311977436929',
    projectId: 'flutterespcontroller',
    authDomain: 'flutterespcontroller.firebaseapp.com',
    databaseURL: 'https://flutterespcontroller-default-rtdb.firebaseio.com',
    storageBucket: 'flutterespcontroller.firebasestorage.app',
    measurementId: 'G-4HFJWMYGXP',
  );

}